#!/bin/bash

## /build - parent dir for everything
##      \__ /payload - directory containing all files to be compiled 
##                     into a single payload.
##              \__ /installer - shell script installer for Splunk
##              \__ /splunkforwarder.tgz - Splunk package

WD=$(pwd)

BUILD_DIR=./build
PAYLOAD_DIR=$BUILD_DIR/payload

cd $BUILD_DIR 

tar -czf splunkinstaller.tgz payload


cat > $BUILD_DIR/installer << EOL
#!/bin/bash

echo ""
echo "Self extracting installer for Splunk"
echo ""

export TMPDIR=`mktemp -d /tmp/selfextract.XXXXXX`

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`
tail -n+$ARCHIVE $0 | tar xzv -C $TMPDIR

CDIR=`pwd`
cd $TMPDIR
./installer

cd $CDIR
rm -rf $TMPDIR

exit 0

__ARCHIVE_BELOW__
EOL

# Add the package to the end of the installer script.
cat $PACKAGE >> $BUILD_DIR/installer