#!/bin/bash

INIT="systemd"

Help()
{
    echo "Install the Splunk Universal Forwarder"
    echo 
    echo "Syntax: installer [-h]"
    echo "i             init system to use (systemd, init)"
    echo "h             print help"
}

while getopts ":hi:" option; do
    case $option in
        h) # display help message
        Help
        exit;;
        i) INIT=$OPTARG;;
        \?) # invalid option
        echo "Error: invalid option specified"
        exit;;
    esac
done

SystemDEnableBootStart()
{
    bin/splunk enable boot-start -systemd-managed 1 --accept-license --answer-yes --no-prompt
    if [ $? -ne 0 ]; then
        echo "Error enabling boot-start."
        exit 1
    fi
    systemctl start SplunkForwarder
    if [ $? -ne 0 ]; then
        exit 1
    fi
}

InitDEnableBootStart()
{
    bin/splunk enable boot-start -systemd-managed 0 --accept-license --answer-yes --no-prompt
    if [ $? -ne 0 ]; then
        echo "Error enabling boot-start."
        exit 1
    fi
    service splunk start
    if [ $? -ne 0 ]; then
        exit 1
    fi
}

tar xzf splunkforwarder.tgz -C /opt
if [ $? -ne 0 ]; then
    echo "Error extracting installer package."
    exit 1
fi

cd /opt/splunkforwarder

case $INIT in
    "init") InitDEnableBootStart 
    "systemd") SystemDEnableBootStart
    *) SystemDEnableBootStart
esac

exit 0